add CONTRIBUTE.md file
jdi-testing/jdi-python pull request #40
Opened 2021-04-28 10:54 UTC by yumalkhasyan

2021-04-28 19:36 UTC, zhidelev requested changes
Please don't pay any attention to failed Pypy build - it does not work with pywin32 for now 😿

2021-04-28 19:36 UTC, zhidelev commented on CONTRIBUTE.md
> +# Contributing to this repository
Rename CONTRIBUTE.md to CONTRIBUTING.md

2021-04-28 19:36 UTC, zhidelev commented on CONTRIBUTE.md
> +-   Have you read the [Best Practices for Managing Secrets](https://elearn.epam.com/courses/course-v1:EPAM+5SCSS+0620/courseware/4b94c749c309409ea878fb7916be316b/ae4553f7cd524229b42f260b0ac692ed/1?ac
add "For EPAM employees only" before "Have you read the..."

2021-04-28 19:36 UTC, zhidelev commented on CONTRIBUTE.md
> +Before you make your changes, check to see if an [issue exists](https://github.com/jdi-testing/jdi-python/issues) already for the change you want to make.
Rephrase to "Before you make your changes, check if an issue already exists for the change you want to make."

2021-04-28 19:36 UTC, zhidelev commented on CONTRIBUTE.md
> +Also don't forget to set up environment variable `TEST_PASSWORD`.
Put this phrase before ```bash...``` and rephrase to "Please don't forget to set up the environment variable TEST_PASSWORD."

2021-04-28 19:36 UTC, zhidelev commented on CONTRIBUTE.md
> +-   This site is powered by Python 3.8.
Change to "Python 3.8 is used for this project."

2021-04-28 19:36 UTC, zhidelev commented on CONTRIBUTE.md
> +Also don't forget to set up environment variable `TEST_PASSWORD`.
Also, add an example:
For Windows ```set TEST_PASSWORD=```

2021-04-29 13:00 UTC, yumalkhasyan commented
> Please don't pay any attention to failed Pypy build - it does not work with pywin32 for now 😿

Yep, I guessed so. I did my best yesterday trying to fix this but failed.
Although, do we really need those PyPy builds?

Also thanks for reviewing!

2021-04-29 16:32 UTC, zhidelev commented
> 
> 
> > Please don't pay any attention to failed Pypy build - it does not work with pywin32 for now 😿
> 
> Yep, I guessed so. I did my best yesterday trying to fix this but failed.
> Although, do we really need those PyPy builds?
> 
> Also thanks for reviewing!

No problem 🙂 Ok, let's remove Pypy builds. We can add them back any moment in future 👍

2021-04-29 16:33 UTC, zhidelev reviewed
👍 
Remove Pypy builds and request Approval.

2021-04-30 13:49 UTC, zhidelev approved these changes
👍

2021-04-30 13:50 UTC, merged