issue 51
jdi-testing/jdi-python pull request #60
Opened 2021-05-26 15:00 UTC by VeldinaElena

locally tests work
<img width="409" alt="check_box_test" src="https://user-images.githubusercontent.com/71984635/119683171-1c81e980-be4c-11eb-883c-cbc9229164c4.png">
<img width="452" alt="check_list_test" src="https://user-images.githubusercontent.com/71984635/119683175-1d1a8000-be4c-11eb-863a-ee7131d0cdd6.png">

2021-06-07 21:16 UTC, zhidelev requested changes
Good work 👍 
- [ ] Fix comments
- [x] Rename the title of the PR to "Replace ddt usage with parametrize"
- [ ] Squash all commits in one

2021-06-07 21:16 UTC, zhidelev commented on tests/jdi_uitests_webtests/test/common/check_box_test.py
> +        CommonActionsData.check_action(MSG_FALSE)
Add a new line at the end of the file 🙂

2021-06-07 21:16 UTC, zhidelev commented on tests/jdi_uitests_webtests/test/complex/check_list_test.py
> +
Please sort imports with `isort`.

2021-06-07 21:16 UTC, zhidelev commented on tests/jdi_uitests_webtests/test/common/check_box_test.py
>  import pytest
Please sort imports with `isort`.

2021-06-09 11:11 UTC, VeldinaElena commented on tests/jdi_uitests_webtests/test/common/check_box_test.py
> +        CommonActionsData.check_action(MSG_FALSE)
+

2021-06-09 11:14 UTC, VeldinaElena commented on tests/jdi_uitests_webtests/test/complex/check_list_test.py
> +
*+*

2021-06-10 11:27 UTC, merged