Bumping dependencies and test site
jdi-testing/jdi-python pull request #69
Opened 2024-03-12 09:17 UTC by vklonin

2024-03-18 14:26 UTC, pnatashap requested changes

2024-03-18 14:26 UTC, pnatashap commented on .github/workflows/jdi-python.yml
> +        pytest -v -m "not unit"
давай еще запуск на firefox тоже сделаем

2024-03-19 10:09 UTC, vklonin commented on .github/workflows/jdi-python.yml
>        matrix:
переключил

2024-03-19 10:09 UTC, vklonin commented on .github/workflows/jdi-python.yml
>      steps:
сделал

2024-03-19 10:09 UTC, vklonin commented on .github/workflows/jdi-python.yml
> +        pytest -v -m "not unit"
сделал

2024-03-19 14:56 UTC, pnatashap approved these changes

2024-03-19 14:57 UTC, pnatashap approved these changes

2024-03-20 10:32 UTC, merged